import { AppThemeProvider } from "@/components/theme/AppThemeProvider";
import "../globals.css";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // return (
  //   <html lang="en">
  //     <body>{children}</body>
  //   </html>
  // )
  return (
    <html lang="en" suppressHydrationWarning
      style={{
        "--primary-color": "#3b82f6",
        "--secondary-color": "#2563eb"
      } as React.CSSProperties}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
